version: '2'
services:
  kosmtik:
    image: kosmtik:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/openstreetmap-carto
    ports:
      - "127.0.0.1:6789:6789"
    environment:
      - PGHOST=172.25.0.1
      - PGUSER=mapclient
